version: '3.8'

services:
  src:
    image: src
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080

  postgres:
    image: postgres
    container_name: metro_db
    restart: always
    environment:
      POSTGRES_USER: ken_kaneki
      POSTGRES_PASSWORD: autoshyektagoru
      POSTGRES_DB: metro_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    user: "postgres"

volumes:
  postgres_data:
